language: ruby

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7

gemfile:
  - gemfiles/Gemfile.rails-6.0
  - gemfiles/Gemfile.rails-5.2
  - gemfiles/Gemfile.rails-5.1
  - gemfiles/Gemfile.rails-5.0
  - gemfiles/Gemfile.rails-4.2

matrix:
  exclude:
    - rvm: 2.2
      gemfile: gemfiles/Gemfile.rails-6.0
    - rvm: 2.3
      gemfile: gemfiles/Gemfile.rails-6.0
    - rvm: 2.4
      gemfile: gemfiles/Gemfile.rails-6.0
    - rvm: 2.2
      gemfile: gemfiles/Gemfile.rails-5.2
    - rvm: 2.7
      gemfile: gemfiles/Gemfile.rails-4.2

before_script: "bundle update"

cache: bundler

script: "bundle exec rake test"
